name: 'Format Node.js Code'
description: 'Runs npm run lint:fix'
inputs:
  path:
    description: 'Path to the node repository'
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 20.x

    - name: Cache Node.js modules
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/**/package-lock.json', inputs.path)) }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Run lint:fix
      run: npm run lint:fix
      shell: bash
      working-directory: ${{ inputs.path }}
