changelog:
  exclude:
    authors:
      - renovate[bot]
      - dependabot[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Breaking change
    - title: New Features 💎
      labels:
        - Feature
    - title: Fixes ⛑️
      labels:
        - Fix
    - title: Other Changes 🖇️
      labels:
        - "*"
