/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { AssociationDelegatedAuthenticationData } from './associationDelegatedAuthenticationData';

export class AssociationFinaliseRequest {
    /**
    * The list of unique identifiers of the resources that you are associating with the SCA device.  Maximum: 5 strings.
    */
    'ids': Array<string>;
    'strongCustomerAuthentication': AssociationDelegatedAuthenticationData;
    /**
    * The type of resource that you are associating with the SCA device.  Possible value: **PaymentInstrument**
    */
    'type': AssociationFinaliseRequest.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>"
        },
        {
            "name": "strongCustomerAuthentication",
            "baseName": "strongCustomerAuthentication",
            "type": "AssociationDelegatedAuthenticationData"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AssociationFinaliseRequest.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return AssociationFinaliseRequest.attributeTypeMap;
    }
}

export namespace AssociationFinaliseRequest {
    export enum TypeEnum {
        PaymentInstrument = <any> 'PaymentInstrument'
    }
}
