/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { BalanceAccountConfiguration } from "./balanceAccountConfiguration";
import { Link } from "./link";


export class BalanceAccountConfigurations {
    /**
    * Contains a list of the Balance Account payout schedules.
    */
    "balanceAccountPayoutSchedules": Array<BalanceAccountConfiguration>;
    "link": Link;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "balanceAccountPayoutSchedules",
            "baseName": "balanceAccountPayoutSchedules",
            "type": "Array<BalanceAccountConfiguration>",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "Link",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BalanceAccountConfigurations.attributeTypeMap;
    }

    public constructor() {
    }
}

