/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Condition } from './condition';

export class BalanceWebhookSettingAllOf {
    /**
    * The list of settings and criteria for triggering the [balance webhook](https://docs.adyen.com/api-explorer/balance-webhooks/latest/post/balanceAccount.balance.updated).
    */
    'conditions'?: Array<Condition>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<Condition>"
        }    ];

    static getAttributeTypeMap() {
        return BalanceWebhookSettingAllOf.attributeTypeMap;
    }
}

