/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { CardOrderItemDeliveryStatus } from './cardOrderItemDeliveryStatus';

export class CardOrderItem {
    /**
    * The unique identifier of the balance platform.
    */
    'balancePlatform'?: string;
    'card'?: CardOrderItemDeliveryStatus;
    /**
    * The unique identifier of the card order item.
    */
    'cardOrderItemId'?: string;
    /**
    * The date and time when the event was triggered, in ISO 8601 extended format. For example, **2020-12-18T10:15:30+01:00**.
    */
    'creationDate'?: Date;
    /**
    * The ID of the resource.
    */
    'id'?: string;
    /**
    * The unique identifier of the payment instrument related to the card order item.
    */
    'paymentInstrumentId'?: string;
    'pin'?: CardOrderItemDeliveryStatus;
    /**
    * The shipping method used to deliver the card or the PIN.
    */
    'shippingMethod'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balancePlatform",
            "baseName": "balancePlatform",
            "type": "string"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "CardOrderItemDeliveryStatus"
        },
        {
            "name": "cardOrderItemId",
            "baseName": "cardOrderItemId",
            "type": "string"
        },
        {
            "name": "creationDate",
            "baseName": "creationDate",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "paymentInstrumentId",
            "baseName": "paymentInstrumentId",
            "type": "string"
        },
        {
            "name": "pin",
            "baseName": "pin",
            "type": "CardOrderItemDeliveryStatus"
        },
        {
            "name": "shippingMethod",
            "baseName": "shippingMethod",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CardOrderItem.attributeTypeMap;
    }
}

