/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Amount } from "./amount";
import { CreateScaInformation } from "./createScaInformation";
import { Scope } from "./scope";
import { TransferType } from "./transferType";


export class CreateTransferLimitRequest {
    "amount": Amount;
    /**
    * The date and time when the transfer limit becomes inactive. If you do not specify an end date, the limit stays active until you override it with a new limit.  Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime): **YYYY-MM-DDThh:mm:ss.sssTZD**
    */
    "endsAt"?: Date;
    /**
    * Your reference for the transfer limit.
    */
    "reference"?: string;
    "scaInformation"?: CreateScaInformation | null;
    "scope": Scope;
    /**
    * The date and time when the transfer limit becomes active. If you specify a date in the future, we will schedule a transfer limit.  Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime): **YYYY-MM-DDThh:mm:ss.sssTZD**
    */
    "startsAt"?: Date;
    "transferType": TransferType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "endsAt",
            "baseName": "endsAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "scaInformation",
            "baseName": "scaInformation",
            "type": "CreateScaInformation | null",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "Scope",
            "format": ""
        },
        {
            "name": "startsAt",
            "baseName": "startsAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "transferType",
            "baseName": "transferType",
            "type": "TransferType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateTransferLimitRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace CreateTransferLimitRequest {
}
