/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class PinChangeResponse {
    /**
    * The status of the request for PIN change.  Possible values: **completed**, **pending**, **unavailable**.
    */
    'status': PinChangeResponse.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "PinChangeResponse.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return PinChangeResponse.attributeTypeMap;
    }
}

export namespace PinChangeResponse {
    export enum StatusEnum {
        Completed = <any> 'completed',
        Pending = <any> 'pending',
        Unavailable = <any> 'unavailable'
    }
}
