/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class PlatformPaymentConfiguration {
    /**
    * Three-letter [ISO currency code](https://docs.adyen.com/development-resources/currency-codes) 
    * to lock the balance account to.  
    * 
    * By default, FX is not applied to the `PaymentFee` split type.  
    * Setting this field enables FX for `PaymentFee` as well.
    */
    "lockedCurrency"?: string;
    /**
    * Specifies at what time a sales day ends for this account.  Possible values: Time in **\"HH:MM\"** format. **HH** ranges from **00** to **07**. **MM** must be **00**.  Default value: **\"00:00\"**.
    */
    "salesDayClosingTime"?: string;
    /**
    * Specifies after how many business days the funds in a settlement batch are made available in this balance account.  Possible values: **1** to **20**, or **null**.  Default value: **null**.
    */
    "settlementDelayDays"?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lockedCurrency",
            "baseName": "lockedCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesDayClosingTime",
            "baseName": "salesDayClosingTime",
            "type": "string",
            "format": "time"
        },
        {
            "name": "settlementDelayDays",
            "baseName": "settlementDelayDays",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return PlatformPaymentConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

