/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { ActiveNetworkTokensRestriction } from './activeNetworkTokensRestriction';
import { BrandVariantsRestriction } from './brandVariantsRestriction';
import { CounterpartyBankRestriction } from './counterpartyBankRestriction';
import { CountriesRestriction } from './countriesRestriction';
import { DayOfWeekRestriction } from './dayOfWeekRestriction';
import { DifferentCurrenciesRestriction } from './differentCurrenciesRestriction';
import { EntryModesRestriction } from './entryModesRestriction';
import { InternationalTransactionRestriction } from './internationalTransactionRestriction';
import { MatchingTransactionsRestriction } from './matchingTransactionsRestriction';
import { MatchingValuesRestriction } from './matchingValuesRestriction';
import { MccsRestriction } from './mccsRestriction';
import { MerchantNamesRestriction } from './merchantNamesRestriction';
import { MerchantsRestriction } from './merchantsRestriction';
import { ProcessingTypesRestriction } from './processingTypesRestriction';
import { RiskScoresRestriction } from './riskScoresRestriction';
import { SameAmountRestriction } from './sameAmountRestriction';
import { SameCounterpartyRestriction } from './sameCounterpartyRestriction';
import { TimeOfDayRestriction } from './timeOfDayRestriction';
import { TotalAmountRestriction } from './totalAmountRestriction';

export class TransactionRuleRestrictions {
    'activeNetworkTokens'?: ActiveNetworkTokensRestriction | null;
    'brandVariants'?: BrandVariantsRestriction | null;
    'counterpartyBank'?: CounterpartyBankRestriction | null;
    'countries'?: CountriesRestriction | null;
    'dayOfWeek'?: DayOfWeekRestriction | null;
    'differentCurrencies'?: DifferentCurrenciesRestriction | null;
    'entryModes'?: EntryModesRestriction | null;
    'internationalTransaction'?: InternationalTransactionRestriction | null;
    'matchingTransactions'?: MatchingTransactionsRestriction | null;
    'matchingValues'?: MatchingValuesRestriction | null;
    'mccs'?: MccsRestriction | null;
    'merchantNames'?: MerchantNamesRestriction | null;
    'merchants'?: MerchantsRestriction | null;
    'processingTypes'?: ProcessingTypesRestriction | null;
    'riskScores'?: RiskScoresRestriction | null;
    'sameAmountRestriction'?: SameAmountRestriction | null;
    'sameCounterpartyRestriction'?: SameCounterpartyRestriction | null;
    'timeOfDay'?: TimeOfDayRestriction | null;
    'totalAmount'?: TotalAmountRestriction | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activeNetworkTokens",
            "baseName": "activeNetworkTokens",
            "type": "ActiveNetworkTokensRestriction | null"
        },
        {
            "name": "brandVariants",
            "baseName": "brandVariants",
            "type": "BrandVariantsRestriction | null"
        },
        {
            "name": "counterpartyBank",
            "baseName": "counterpartyBank",
            "type": "CounterpartyBankRestriction | null"
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "CountriesRestriction | null"
        },
        {
            "name": "dayOfWeek",
            "baseName": "dayOfWeek",
            "type": "DayOfWeekRestriction | null"
        },
        {
            "name": "differentCurrencies",
            "baseName": "differentCurrencies",
            "type": "DifferentCurrenciesRestriction | null"
        },
        {
            "name": "entryModes",
            "baseName": "entryModes",
            "type": "EntryModesRestriction | null"
        },
        {
            "name": "internationalTransaction",
            "baseName": "internationalTransaction",
            "type": "InternationalTransactionRestriction | null"
        },
        {
            "name": "matchingTransactions",
            "baseName": "matchingTransactions",
            "type": "MatchingTransactionsRestriction | null"
        },
        {
            "name": "matchingValues",
            "baseName": "matchingValues",
            "type": "MatchingValuesRestriction | null"
        },
        {
            "name": "mccs",
            "baseName": "mccs",
            "type": "MccsRestriction | null"
        },
        {
            "name": "merchantNames",
            "baseName": "merchantNames",
            "type": "MerchantNamesRestriction | null"
        },
        {
            "name": "merchants",
            "baseName": "merchants",
            "type": "MerchantsRestriction | null"
        },
        {
            "name": "processingTypes",
            "baseName": "processingTypes",
            "type": "ProcessingTypesRestriction | null"
        },
        {
            "name": "riskScores",
            "baseName": "riskScores",
            "type": "RiskScoresRestriction | null"
        },
        {
            "name": "sameAmountRestriction",
            "baseName": "sameAmountRestriction",
            "type": "SameAmountRestriction | null"
        },
        {
            "name": "sameCounterpartyRestriction",
            "baseName": "sameCounterpartyRestriction",
            "type": "SameCounterpartyRestriction | null"
        },
        {
            "name": "timeOfDay",
            "baseName": "timeOfDay",
            "type": "TimeOfDayRestriction | null"
        },
        {
            "name": "totalAmount",
            "baseName": "totalAmount",
            "type": "TotalAmountRestriction | null"
        }    ];

    static getAttributeTypeMap() {
        return TransactionRuleRestrictions.attributeTypeMap;
    }
}

