/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class WalletProviderDeviceType {
    /**
    * Defines how the condition must be evaluated.
    */
    'operation': string;
    'value'?: Array<WalletProviderDeviceType.ValueEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "operation",
            "baseName": "operation",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<WalletProviderDeviceType.ValueEnum>"
        }    ];

    static getAttributeTypeMap() {
        return WalletProviderDeviceType.attributeTypeMap;
    }
}

export namespace WalletProviderDeviceType {
    export enum ValueEnum {
        Card = 'CARD',
        MobilePhone = 'MOBILE_PHONE',
        Other = 'OTHER',
        Pc = 'PC',
        TabletOrEreader = 'TABLET_OR_EREADER',
        Unknown = 'UNKNOWN',
        WatchOrWristband = 'WATCH_OR_WRISTBAND',
        Wearable = 'WEARABLE'
    }
}
