language: node_js
node_js:
  - stable
before_install:
  - rm -rf package-lock.json node_modules
cache:
  directories:
    - "node_modules"
script:
  - npm run lint:fix
  - npm run lint
  - npm run test
jobs:
  include:
    - stage: npm release
      node_js: "stable"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: 
          tags: true
