sonar.organization=adyen
sonar.projectKey=Adyen_adyen-node-api-library
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=src/__mocks__/**/*,src/__tests__/**/*

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/typings/**/*
sonar.cpd.exclusions=src/typings/**/*
