/*
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Amount } from './amount';

export class DetailBalance {
    /**
    * The list of balances held by the account.
    */
    'balance'?: Array<Amount>;
    /**
    * The list of on hold balances held by the account.
    */
    'onHoldBalance'?: Array<Amount>;
    /**
    * The list of pending balances held by the account.
    */
    'pendingBalance'?: Array<Amount>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balance",
            "baseName": "balance",
            "type": "Array<Amount>"
        },
        {
            "name": "onHoldBalance",
            "baseName": "onHoldBalance",
            "type": "Array<Amount>"
        },
        {
            "name": "pendingBalance",
            "baseName": "pendingBalance",
            "type": "Array<Amount>"
        }    ];

    static getAttributeTypeMap() {
        return DetailBalance.attributeTypeMap;
    }
}

