/*
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export * from './accountDetailBalance';
export * from './accountHolderBalanceRequest';
export * from './accountHolderBalanceResponse';
export * from './accountHolderTransactionListRequest';
export * from './accountHolderTransactionListResponse';
export * from './accountTransactionList';
export * from './amount';
export * from './bankAccountDetail';
export * from './debitAccountHolderRequest';
export * from './debitAccountHolderResponse';
export * from './detailBalance';
export * from './errorFieldType';
export * from './fieldType';
export * from './payoutAccountHolderRequest';
export * from './payoutAccountHolderResponse';
export * from './refundFundsTransferRequest';
export * from './refundFundsTransferResponse';
export * from './refundNotPaidOutTransfersRequest';
export * from './refundNotPaidOutTransfersResponse';
export * from './serviceError';
export * from './setupBeneficiaryRequest';
export * from './setupBeneficiaryResponse';
export * from './split';
export * from './splitAmount';
export * from './transaction';
export * from './transactionListForAccount';
export * from './transferFundsRequest';
export * from './transferFundsResponse';


import { AccountDetailBalance } from './accountDetailBalance';
import { AccountHolderBalanceRequest } from './accountHolderBalanceRequest';
import { AccountHolderBalanceResponse } from './accountHolderBalanceResponse';
import { AccountHolderTransactionListRequest } from './accountHolderTransactionListRequest';
import { AccountHolderTransactionListResponse } from './accountHolderTransactionListResponse';
import { AccountTransactionList } from './accountTransactionList';
import { Amount } from './amount';
import { BankAccountDetail } from './bankAccountDetail';
import { DebitAccountHolderRequest } from './debitAccountHolderRequest';
import { DebitAccountHolderResponse } from './debitAccountHolderResponse';
import { DetailBalance } from './detailBalance';
import { ErrorFieldType } from './errorFieldType';
import { FieldType } from './fieldType';
import { PayoutAccountHolderRequest } from './payoutAccountHolderRequest';
import { PayoutAccountHolderResponse } from './payoutAccountHolderResponse';
import { RefundFundsTransferRequest } from './refundFundsTransferRequest';
import { RefundFundsTransferResponse } from './refundFundsTransferResponse';
import { RefundNotPaidOutTransfersRequest } from './refundNotPaidOutTransfersRequest';
import { RefundNotPaidOutTransfersResponse } from './refundNotPaidOutTransfersResponse';
import { ServiceError } from './serviceError';
import { SetupBeneficiaryRequest } from './setupBeneficiaryRequest';
import { SetupBeneficiaryResponse } from './setupBeneficiaryResponse';
import { Split } from './split';
import { SplitAmount } from './splitAmount';
import { Transaction } from './transaction';
import { TransactionListForAccount } from './transactionListForAccount';
import { TransferFundsRequest } from './transferFundsRequest';
import { TransferFundsResponse } from './transferFundsResponse';

/* tslint:disable:no-unused-variable */
let primitives = [
                    "string",
                    "boolean",
                    "double",
                    "integer",
                    "long",
                    "float",
                    "number",
                    "any"
                 ];

let enumsMap: {[index: string]: any} = {
        "AccountHolderTransactionListRequest.TransactionStatusesEnum": AccountHolderTransactionListRequest.TransactionStatusesEnum,
        "FieldType.FieldNameEnum": FieldType.FieldNameEnum,
        "PayoutAccountHolderRequest.PayoutSpeedEnum": PayoutAccountHolderRequest.PayoutSpeedEnum,
        "PayoutAccountHolderResponse.PayoutSpeedEnum": PayoutAccountHolderResponse.PayoutSpeedEnum,
        "Split.TypeEnum": Split.TypeEnum,
        "Transaction.TransactionStatusEnum": Transaction.TransactionStatusEnum,
}

let typeMap: {[index: string]: any} = {
    "AccountDetailBalance": AccountDetailBalance,
    "AccountHolderBalanceRequest": AccountHolderBalanceRequest,
    "AccountHolderBalanceResponse": AccountHolderBalanceResponse,
    "AccountHolderTransactionListRequest": AccountHolderTransactionListRequest,
    "AccountHolderTransactionListResponse": AccountHolderTransactionListResponse,
    "AccountTransactionList": AccountTransactionList,
    "Amount": Amount,
    "BankAccountDetail": BankAccountDetail,
    "DebitAccountHolderRequest": DebitAccountHolderRequest,
    "DebitAccountHolderResponse": DebitAccountHolderResponse,
    "DetailBalance": DetailBalance,
    "ErrorFieldType": ErrorFieldType,
    "FieldType": FieldType,
    "PayoutAccountHolderRequest": PayoutAccountHolderRequest,
    "PayoutAccountHolderResponse": PayoutAccountHolderResponse,
    "RefundFundsTransferRequest": RefundFundsTransferRequest,
    "RefundFundsTransferResponse": RefundFundsTransferResponse,
    "RefundNotPaidOutTransfersRequest": RefundNotPaidOutTransfersRequest,
    "RefundNotPaidOutTransfersResponse": RefundNotPaidOutTransfersResponse,
    "ServiceError": ServiceError,
    "SetupBeneficiaryRequest": SetupBeneficiaryRequest,
    "SetupBeneficiaryResponse": SetupBeneficiaryResponse,
    "Split": Split,
    "SplitAmount": SplitAmount,
    "Transaction": Transaction,
    "TransactionListForAccount": TransactionListForAccount,
    "TransferFundsRequest": TransferFundsRequest,
    "TransferFundsResponse": TransferFundsResponse,
}

export class ObjectSerializer {
    public static findCorrectType(data: any, expectedType: string) {
        if (data == undefined) {
            return expectedType;
        } else if (primitives.indexOf(expectedType.toLowerCase()) !== -1) {
            return expectedType;
        } else if (expectedType === "Date") {
            return expectedType;
        } else {
            if (enumsMap[expectedType]) {
                return expectedType;
            }

            if (!typeMap[expectedType]) {
                return expectedType; // w/e we don't know the type
            }

            // Check the discriminator
            let discriminatorProperty = typeMap[expectedType].discriminator;
            if (discriminatorProperty == null) {
                return expectedType; // the type does not have a discriminator. use it.
            } else {
                if (data[discriminatorProperty]) {
                    var discriminatorType = data[discriminatorProperty];
                    if(typeMap[discriminatorType]){
                        return discriminatorType; // use the type given in the discriminator
                    } else {
                        return expectedType; // discriminator did not map to a type
                    }
                } else {
                    return expectedType; // discriminator was not present (or an empty string)
                }
            }
        }
    }

    public static serialize(data: any, type: string) {
        if (data == undefined) {
            return data;
        } else if (primitives.indexOf(type.toLowerCase()) !== -1) {
            return data;
        } else if (type.lastIndexOf("Array<", 0) === 0) { // string.startsWith pre es6
            let subType: string = type.replace("Array<", ""); // Array<Type> => Type>
            subType = subType.substring(0, subType.length - 1); // Type> => Type
            let transformedData: any[] = [];
            for (let index = 0; index < data.length; index++) {
                let datum = data[index];
                transformedData.push(ObjectSerializer.serialize(datum, subType));
            }
            return transformedData;
        } else if (type === "Date") {
            return data.toISOString();
        } else if (type === "SaleToAcquirerData") {
            const dataString = JSON.stringify(data);
            return Buffer.from(dataString).toString("base64");
        } else {
            if (enumsMap[type]) {
                return data;
            }
            if (!typeMap[type]) { // in case we dont know the type
                return data;
            }

            // Get the actual type of this object
            type = this.findCorrectType(data, type);

            // get the map for the correct type.
            let attributeTypes = typeMap[type].getAttributeTypeMap();
            let instance: {[index: string]: any} = {};
            for (let index = 0; index < attributeTypes.length; index++) {
                let attributeType = attributeTypes[index];
                instance[attributeType.baseName] = ObjectSerializer.serialize(data[attributeType.name], attributeType.type);
            }
            return instance;
        }
    }

    public static deserialize(data: any, type: string) {
        // polymorphism may change the actual type.
        type = ObjectSerializer.findCorrectType(data, type);
        if (data == undefined) {
            return data;
        } else if (primitives.indexOf(type.toLowerCase()) !== -1) {
            return data;
        } else if (type.lastIndexOf("Array<", 0) === 0) { // string.startsWith pre es6
            let subType: string = type.replace("Array<", ""); // Array<Type> => Type>
            subType = subType.substring(0, subType.length - 1); // Type> => Type
            let transformedData: any[] = [];
            for (let index = 0; index < data.length; index++) {
                let datum = data[index];
                transformedData.push(ObjectSerializer.deserialize(datum, subType));
            }
            return transformedData;
        } else if (type === "Date") {
            return new Date(data);
        } else {
            if (enumsMap[type]) {// is Enum
                return data;
            }

            if (!typeMap[type]) { // dont know the type
                return data;
            }
            let instance = new typeMap[type]();
            let attributeTypes = typeMap[type].getAttributeTypeMap();
            for (let index = 0; index < attributeTypes.length; index++) {
                let attributeType = attributeTypes[index];
                instance[attributeType.name] = ObjectSerializer.deserialize(data[attributeType.baseName], attributeType.type);
            }
            return instance;
        }
    }
}
