/*
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Amount } from "./amount";
import { CapitalBalance } from "./capitalBalance";
import { Counterparty } from "./counterparty";
import { Fee } from "./fee";
import { Repayment } from "./repayment";


export class CapitalGrant {
    "amount"?: Amount;
    "balances": CapitalBalance;
    "counterparty"?: Counterparty;
    "fee"?: Fee;
    /**
    * The identifier of the grant account used for the grant.
    */
    "grantAccountId": string;
    /**
    * The identifier of the grant offer that has been selected and from which the grant details will be used.
    */
    "grantOfferId": string;
    /**
    * The identifier of the grant reference.
    */
    "id": string;
    "repayment"?: Repayment;
    /**
    * The current status of the grant. Possible values: **Pending**, **Active**, **Repaid**, **WrittenOff**, **Failed**, **Revoked**.
    */
    "status": CapitalGrant.StatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "balances",
            "baseName": "balances",
            "type": "CapitalBalance",
            "format": ""
        },
        {
            "name": "counterparty",
            "baseName": "counterparty",
            "type": "Counterparty",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "Fee",
            "format": ""
        },
        {
            "name": "grantAccountId",
            "baseName": "grantAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "grantOfferId",
            "baseName": "grantOfferId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "repayment",
            "baseName": "repayment",
            "type": "Repayment",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CapitalGrant.StatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CapitalGrant.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace CapitalGrant {
    export enum StatusEnum {
        Pending = 'Pending',
        Active = 'Active',
        Repaid = 'Repaid',
        Failed = 'Failed',
        WrittenOff = 'WrittenOff',
        Revoked = 'Revoked'
    }
}
