/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


import getJsonResponse from "../../helpers/getJsonResponse";
import Service from "../../service";
import Client from "../../client";
import { IRequest } from "../../typings/requestOptions";
import Resource from "../resource";

import { ObjectSerializer } from "../../typings/balancePlatform/objectSerializer";
import { ListMandatesResponse } from "../../typings/balancePlatform/models";
import { Mandate } from "../../typings/balancePlatform/models";
import { MandateUpdate } from "../../typings/balancePlatform/models";

/**
 * API handler for DirectDebitMandatesApi
 */
export class DirectDebitMandatesApi extends Service {

    private readonly API_BASEPATH: string = "https://balanceplatform-api-test.adyen.com/bcl/v2";
    private baseUrl: string;

    public constructor(client: Client){
        super(client);
        this.baseUrl = this.createBaseUrl(this.API_BASEPATH);
    }

    /**
    * @summary Cancel a mandate
    * @param mandateId {@link string } The unique identifier of the mandate.
    * @param requestOptions {@link IRequest.Options }
    * @return {@link void }
    */
    public async cancelMandate(mandateId: string, requestOptions?: IRequest.Options): Promise<void> {
        const endpoint = `${this.baseUrl}/mandates/{mandateId}/cancel`
            .replace("{" + "mandateId" + "}", encodeURIComponent(String(mandateId)));
        const resource = new Resource(this, endpoint);
        
        await getJsonResponse<string, void>(
            resource,
            "",
            { ...requestOptions, method: "POST" }
        );
    }

    /**
    * @summary Get a list of mandates
    * @param requestOptions {@link IRequest.Options }
    * @param balanceAccountId {@link string } The unique identifier of the balance account linked to the payment instrument.
    * @param paymentInstrumentId {@link string } The unique identifier of the payment instrument linked to the mandate.
    * @param cursor {@link string } The pagination cursor returned in a previous GET &#x60;/mandates&#x60; request.
    * @return {@link ListMandatesResponse }
    */
    public async getListOfMandates(balanceAccountId?: string, paymentInstrumentId?: string, cursor?: string, requestOptions?: IRequest.Options): Promise<ListMandatesResponse> {
        const endpoint = `${this.baseUrl}/mandates`;
        const resource = new Resource(this, endpoint);
        
        const hasDefinedQueryParams = balanceAccountId ?? paymentInstrumentId ?? cursor;
        if(hasDefinedQueryParams) {
            if(!requestOptions) requestOptions = {};
            if(!requestOptions.params) requestOptions.params = {};
            if(balanceAccountId) requestOptions.params["balanceAccountId"] = balanceAccountId;
            if(paymentInstrumentId) requestOptions.params["paymentInstrumentId"] = paymentInstrumentId;
            if(cursor) requestOptions.params["cursor"] = cursor;
        }
        const response = await getJsonResponse<string, ListMandatesResponse>(
            resource,
            "",
            { ...requestOptions, method: "GET" }
        );

        return ObjectSerializer.deserialize(response, "ListMandatesResponse");
    }

    /**
    * @summary Get a specific mandate
    * @param mandateId {@link string } The unique identifier of the mandate.
    * @param requestOptions {@link IRequest.Options }
    * @return {@link Mandate }
    */
    public async getMandateById(mandateId: string, requestOptions?: IRequest.Options): Promise<Mandate> {
        const endpoint = `${this.baseUrl}/mandates/{mandateId}`
            .replace("{" + "mandateId" + "}", encodeURIComponent(String(mandateId)));
        const resource = new Resource(this, endpoint);
        
        const response = await getJsonResponse<string, Mandate>(
            resource,
            "",
            { ...requestOptions, method: "GET" }
        );

        return ObjectSerializer.deserialize(response, "Mandate");
    }

    /**
    * @summary Amend a mandate
    * @param mandateId {@link string } The unique identifier of the mandate.
    * @param mandateUpdate {@link MandateUpdate } 
    * @param requestOptions {@link IRequest.Options }
    * @return {@link void }
    */
    public async updateMandate(mandateId: string, mandateUpdate: MandateUpdate, requestOptions?: IRequest.Options): Promise<void> {
        const endpoint = `${this.baseUrl}/mandates/{mandateId}`
            .replace("{" + "mandateId" + "}", encodeURIComponent(String(mandateId)));
        const resource = new Resource(this, endpoint);
        
        const request: MandateUpdate = ObjectSerializer.serialize(mandateUpdate, "MandateUpdate");
        await getJsonResponse<MandateUpdate, void>(
            resource,
            request,
            { ...requestOptions, method: "PATCH" }
        );
    }

}
