/*
 * The version of the OpenAPI document: v68
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class AdditionalDataWallets {

    /**
    * The Android Pay token retrieved from the SDK.
    */
    'androidpayToken'?: string;

    /**
    * The Mastercard Masterpass Transaction ID retrieved from the SDK.
    */
    'masterpassTransactionId'?: string;

    /**
    * The Apple Pay token retrieved from the SDK.
    */
    'paymentToken'?: string;

    /**
    * The Google Pay token retrieved from the SDK.
    */
    'paywithgoogleToken'?: string;

    /**
    * The Samsung Pay token retrieved from the SDK.
    */
    'samsungpayToken'?: string;

    /**
    * The Visa Checkout Call ID retrieved from the SDK.
    */
    'visacheckoutCallId'?: string;
}

