/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { reportWebhooks } from "..";

/**
 * Union type for all supported webhook requests.
 * Allows generic handling of configuration-related webhook events.
 */
export type GenericWebhook = 
    | reportWebhooks.ReportNotificationRequest;

/**
 * Handler for processing ReportWebhooks.
 * 
 * This class provides functionality to deserialize the payload of ReportWebhooks events.
 */
export class ReportWebhooksHandler {

    private readonly payload: Record<string, any>;

    public constructor(jsonPayload: string) {
        this.payload = JSON.parse(jsonPayload);
    }

    /**
     * This method checks the type of the webhook payload and returns the appropriate deserialized object.
     * 
     * @returns A deserialized object of type GenericWebhook.
     * @throws Error if the type is not recognized.
     */
    public getGenericWebhook(): GenericWebhook {
    
        const type = this.payload["type"];
        
        if(Object.values(reportWebhooks.ReportNotificationRequest.TypeEnum).includes(type)) {
            return this.getReportNotificationRequest();
        }
        
        throw new Error("Could not parse the json payload: " + this.payload);

    }

    /**
     * Deserialize the webhook payload into a ReportNotificationRequest
     *
     * @returns Deserialized ReportNotificationRequest object.
     */
    public getReportNotificationRequest(): reportWebhooks.ReportNotificationRequest {
        return reportWebhooks.ObjectSerializer.deserialize(this.payload, "ReportNotificationRequest");
    }

}