/**
 * Adyen Checkout API
 * Adyen Checkout API provides a simple and flexible way to initiate and authorise online payments. You can use the same integration for payments made with cards (including One-Click and 3D Secure), mobile wallets, and local payment methods (e.g. iDEAL and Sofort).  This API reference provides information on available endpoints and how to interact with them. To learn more about the API, visit [Checkout documentation](https://docs.adyen.com/checkout).  ## Authentication Each request to the Checkout API must be signed with an API key. For this, obtain an API Key from your Customer Area, as described in [How to get the API key](https://docs.adyen.com/user-management/how-to-get-the-api-key). Then set this key to the `X-API-Key` header value, for example:  ``` curl -H \"Content-Type: application/json\" \\ -H \"X-API-Key: Your_Checkout_API_key\" \\ ... ``` Note that when going live, you need to generate a new API Key to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).  ## Versioning Checkout API supports versioning of its endpoints through a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://checkout-test.adyen.com/v51/payments ```
 *
 * The version of the OpenAPI document: 51
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class AdditionalDataRiskStandalone {
    /**
    * Raw AVS result received from the acquirer, where available. Example: 7
    */
    'avsResultRaw'?: string;
    /**
    * The Bank Identification Number of a credit card, which is the first six digits of a card number. Required for [tokenized card request](/risk-management/standalone-risk#tokenised-pan-request).
    */
    'bin'?: string;
    /**
    * Raw CVC result received from the acquirer, where available. Example: 1
    */
    'cvcResultRaw'?: string;
    /**
    * Unique identifier or token for the shopper\'s card details.
    */
    'riskToken'?: string;
    /**
    * A Boolean value indicating whether 3DS authentication was completed on this payment. Example: true
    */
    'threeDAuthenticated'?: string;
    /**
    * A Boolean value indicating whether 3DS was offered for this payment. Example: true
    */
    'threeDOffered'?: string;
    /**
    * Required for PayPal payments only. The only supported value is: **paypal**.
    */
    'tokenDataType'?: string;
    /**
    * Allowed values: * **Eligible** — Merchant is protected by PayPal\'s Seller Protection Policy for Unauthorized Payments and Item Not Received. * **PartiallyEligible** — Merchant is protected by PayPal\'s Seller Protection Policy for Item Not Received. * **Ineligible** — Merchant is not protected under the Seller Protection Policy.
    */
    'payPalProtectionEligibility'?: string;
    /**
    * Unique PayPal Customer Account identification number. Character length and limitations: 13 single-byte alphanumeric characters.
    */
    'payPalPayerId'?: string;
    /**
    * Unique transaction ID of the payment.
    */
    'payPalTransactionId'?: string;
    /**
    * Shopper\'s country of residence in the form of ISO standard 3166 2-character country codes.
    */
    'payPalCountryCode'?: string;
    /**
    * Shopper\'s first name.
    */
    'payPalFirstName'?: string;
    /**
    * Shopper\'s last name.
    */
    'payPalLastName'?: string;
    /**
    * Shopper\'s phone number.
    */
    'payPalPhone'?: string;
    /**
    * Shopper\'s email.
    */
    'payPalEmailId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avsResultRaw",
            "baseName": "avsResultRaw",
            "type": "string"
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string"
        },
        {
            "name": "cvcResultRaw",
            "baseName": "cvcResultRaw",
            "type": "string"
        },
        {
            "name": "riskToken",
            "baseName": "risk.token",
            "type": "string"
        },
        {
            "name": "threeDAuthenticated",
            "baseName": "threeDAuthenticated",
            "type": "string"
        },
        {
            "name": "threeDOffered",
            "baseName": "threeDOffered",
            "type": "string"
        },
        {
            "name": "tokenDataType",
            "baseName": "tokenDataType",
            "type": "string"
        },
        {
            "name": "payPalProtectionEligibility",
            "baseName": "PayPal.ProtectionEligibility",
            "type": "string"
        },
        {
            "name": "payPalPayerId",
            "baseName": "PayPal.PayerId",
            "type": "string"
        },
        {
            "name": "payPalTransactionId",
            "baseName": "PayPal.TransactionId",
            "type": "string"
        },
        {
            "name": "payPalCountryCode",
            "baseName": "PayPal.CountryCode",
            "type": "string"
        },
        {
            "name": "payPalFirstName",
            "baseName": "PayPal.FirstName",
            "type": "string"
        },
        {
            "name": "payPalLastName",
            "baseName": "PayPal.LastName",
            "type": "string"
        },
        {
            "name": "payPalPhone",
            "baseName": "PayPal.Phone",
            "type": "string"
        },
        {
            "name": "payPalEmailId",
            "baseName": "PayPal.EmailId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AdditionalDataRiskStandalone.attributeTypeMap;
    }
}

