/*
 * The version of the OpenAPI document: v72
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { PickupInfo } from "./pickupInfo";
import { RentalSurcharges } from "./rentalSurcharges";
import { ReturnInfo } from "./returnInfo";


export class CarRental {
    /**
    * The customer service phone number of the car rental company. * Format: Alphanumeric * maxLength: 17 * For US and CA numbers must be 10 characters in length * Must not contain any special characters such as + or - * Must not start with a space or be all spaces. * Must not be all zeros. * **additionalData key:** `carRental.customerServiceTollFreeNumber`
    */
    "customerServicePhoneNumber"?: string;
    /**
    * Indicates if the customer didn\'t pick up their rental car. * **additionalData key:** `carRental.noShowIndicator`
    */
    "noShow"?: boolean;
    "pickupInfo"?: PickupInfo | null;
    /**
    * Indicates whether the rental rate is daily or weekly. * **additionalData key:** `carRental.rateIndicator`
    */
    "rateType"?: CarRental.RateTypeEnum;
    /**
    * The rental agreement number for the car rental. * Format: ASCII * maxLength: 9 characters * Must not start with a space or be all spaces. * Must not be all zeros. * **additionalData key:** `carRental.rentalAgreementNumber`
    */
    "rentalAgreementNumber"?: string;
    /**
    * The classification of the rental car. * Format: Alphanumeric * maxLength: 4 characters * Must not start with a space or be all spaces. * Must not be all zeros. * **additionalData key:** `carRental.rentalClassId`
    */
    "rentalClassId"?: string;
    /**
    * The number of days the car is rented for. * Format: Numeric * Max value: 9999 * **additionalData key:** `carRental.daysRented`
    */
    "rentalDays"?: number;
    /**
    * Rental rate, in [minor units](https://docs.adyen.com/development-resources/currency-codes). * For example, 2000 means USD 20.00. * Encoding: Numeric * Max value: 10000000000 * Frequency of the rental rate is specified in the rateType field. * **additionalData key:** `carRental.rate`
    */
    "rentalRate"?: number;
    "rentalSurcharges"?: RentalSurcharges | null;
    /**
    * The name of the person renting the car. * Format: ASCII * Must not start with a space or be all spaces. * Must not be all zeros. * **additionalData key:** `carRental.renterName`
    */
    "renterName": string;
    "returnInfo"?: ReturnInfo | null;
    /**
    * Indicates if the goods or services were tax-exempt, or if tax was not collected. * **additionalData key:** `carRental.taxExemptIndicator`
    */
    "taxExempt"?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerServicePhoneNumber",
            "baseName": "customerServicePhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "noShow",
            "baseName": "noShow",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pickupInfo",
            "baseName": "pickupInfo",
            "type": "PickupInfo | null",
            "format": ""
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "CarRental.RateTypeEnum",
            "format": ""
        },
        {
            "name": "rentalAgreementNumber",
            "baseName": "rentalAgreementNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "rentalClassId",
            "baseName": "rentalClassId",
            "type": "string",
            "format": ""
        },
        {
            "name": "rentalDays",
            "baseName": "rentalDays",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "rentalRate",
            "baseName": "rentalRate",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "rentalSurcharges",
            "baseName": "rentalSurcharges",
            "type": "RentalSurcharges | null",
            "format": ""
        },
        {
            "name": "renterName",
            "baseName": "renterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnInfo",
            "baseName": "returnInfo",
            "type": "ReturnInfo | null",
            "format": ""
        },
        {
            "name": "taxExempt",
            "baseName": "taxExempt",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CarRental.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace CarRental {
    export enum RateTypeEnum {
        Daily = 'daily',
        Weekly = 'weekly'
    }
}
