/*
 * The version of the OpenAPI document: v71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Amount } from './models';


export class CheckoutOrderResponse {
    'amount'?: Amount;
    /**
    * The expiry date for the order.
    */
    'expiresAt'?: string;
    /**
    * The encrypted order data.
    */
    'orderData'?: string;
    /**
    * The `pspReference` that belongs to the order.
    */
    'pspReference': string;
    /**
    * The merchant reference for the order.
    */
    'reference'?: string;
    'remainingAmount'?: Amount;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderData",
            "baseName": "orderData",
            "type": "string",
            "format": ""
        },
        {
            "name": "pspReference",
            "baseName": "pspReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "remainingAmount",
            "baseName": "remainingAmount",
            "type": "Amount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckoutOrderResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

