/*
 * The version of the OpenAPI document: v71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { CheckoutForwardRequestCard } from "./checkoutForwardRequestCard";
import { CheckoutForwardRequestOptions } from "./checkoutForwardRequestOptions";
import { CheckoutOutgoingForwardRequest } from "./checkoutOutgoingForwardRequest";


export class CheckoutForwardRequest {
    /**
    * The base URL of the third party API, where Adyen will send the request to forward the payment details.
    */
    "baseUrl": string;
    /**
    * Your merchant account.
    */
    "merchantAccount": string;
    /**
    * Merchant defined payment reference.
    */
    "merchantReference"?: string;
    "options"?: CheckoutForwardRequestOptions | null;
    "paymentMethod"?: CheckoutForwardRequestCard | null;
    "request": CheckoutOutgoingForwardRequest;
    /**
    * Your reference to uniquely identify this shopper, for example user ID or account ID. The value is case-sensitive and must be at least three characters. > Your reference must not include personally identifiable information (PII) such as name or email address.
    */
    "shopperReference": string;
    /**
    * The unique identifier of the token that you want to forward to the third party. This is the `storedPaymentMethodId` you received in the webhook after you created the token.
    */
    "storedPaymentMethodId"?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseUrl",
            "baseName": "baseUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "merchantAccount",
            "baseName": "merchantAccount",
            "type": "string",
            "format": ""
        },
        {
            "name": "merchantReference",
            "baseName": "merchantReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "CheckoutForwardRequestOptions | null",
            "format": ""
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "CheckoutForwardRequestCard | null",
            "format": ""
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "CheckoutOutgoingForwardRequest",
            "format": ""
        },
        {
            "name": "shopperReference",
            "baseName": "shopperReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "storedPaymentMethodId",
            "baseName": "storedPaymentMethodId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckoutForwardRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

