/*
 * The version of the OpenAPI document: v72
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { ApplePayDonations } from "./applePayDonations";
import { CardDonations } from "./cardDonations";
import { GooglePayDonations } from "./googlePayDonations";
import { IdealDonations } from "./idealDonations";
import { PayWithGoogleDonations } from "./payWithGoogleDonations";
import { SepaDirectDebitDonations } from "./sepaDirectDebitDonations";

/**
* The type and required details of a payment method to use.  When `donationToken` is provided, the payment method is derived from the token and this field becomes optional.  If you are [PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide), and make donations using raw card details, you must explicitly provide the payment method details.
*/


/**
 * @type DonationPaymentRequestPaymentMethod
 * Type
 * @export
 */
export type DonationPaymentRequestPaymentMethod = ApplePayDonations | CardDonations | GooglePayDonations | IdealDonations | PayWithGoogleDonations | SepaDirectDebitDonations;

/**
* @type DonationPaymentRequestPaymentMethodClass
    * The type and required details of a payment method to use.  When `donationToken` is provided, the payment method is derived from the token and this field becomes optional.  If you are [PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide), and make donations using raw card details, you must explicitly provide the payment method details.
* @export
*/
export class DonationPaymentRequestPaymentMethodClass {
    
    
    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "applepay": "ApplePayDonations",
        "card": "CardDonations",
        "googlepay": "GooglePayDonations",
        "ideal": "IdealDonations",
        "networkToken": "CardDonations",
        "paywithgoogle": "PayWithGoogleDonations",
        "scheme": "CardDonations",
        "sepadirectdebit": "SepaDirectDebitDonations",
    };
}
