/*
 * The version of the OpenAPI document: v71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Airline } from './airline';

export class EnhancedSchemeData {
    'airline'?: Airline | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "airline",
            "baseName": "airline",
            "type": "Airline | null"
        }    ];

    static getAttributeTypeMap() {
        return EnhancedSchemeData.attributeTypeMap;
    }
}

