/*
 * The version of the OpenAPI document: v71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class LineItem {
    /**
    * Item amount excluding the tax, in minor units.
    */
    'amountExcludingTax'?: number;
    /**
    * Item amount including the tax, in minor units.
    */
    'amountIncludingTax'?: number;
    /**
    * Brand of the item.
    */
    'brand'?: string;
    /**
    * Color of the item.
    */
    'color'?: string;
    /**
    * Description of the line item.
    */
    'description'?: string;
    /**
    * ID of the line item.
    */
    'id'?: string;
    /**
    * Link to the picture of the purchased item.
    */
    'imageUrl'?: string;
    /**
    * Item category, used by the payment methods PayPal and Ratepay.
    */
    'itemCategory'?: string;
    /**
    * Manufacturer of the item.
    */
    'manufacturer'?: string;
    /**
    * Marketplace seller id.
    */
    'marketplaceSellerId'?: string;
    /**
    * Link to the purchased item.
    */
    'productUrl'?: string;
    /**
    * Number of items.
    */
    'quantity'?: number;
    /**
    * Email associated with the given product in the basket (usually in electronic gift cards).
    */
    'receiverEmail'?: string;
    /**
    * Size of the item.
    */
    'size'?: string;
    /**
    * Stock keeping unit.
    */
    'sku'?: string;
    /**
    * Tax amount, in minor units.
    */
    'taxAmount'?: number;
    /**
    * Tax percentage, in minor units.
    */
    'taxPercentage'?: number;
    /**
    * Universal Product Code.
    */
    'upc'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amountExcludingTax",
            "baseName": "amountExcludingTax",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "amountIncludingTax",
            "baseName": "amountIncludingTax",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "brand",
            "baseName": "brand",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemCategory",
            "baseName": "itemCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "marketplaceSellerId",
            "baseName": "marketplaceSellerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "productUrl",
            "baseName": "productUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "receiverEmail",
            "baseName": "receiverEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxAmount",
            "baseName": "taxAmount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taxPercentage",
            "baseName": "taxPercentage",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "upc",
            "baseName": "upc",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LineItem.attributeTypeMap;
    }

    public constructor() {
    }
}

