/*
 * The version of the OpenAPI document: v72
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class LineItem {
    /**
    * Item amount excluding the tax, in [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).
    */
    "amountExcludingTax"?: number;
    /**
    * Item amount including the tax, in [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).
    */
    "amountIncludingTax"?: number;
    /**
    * Brand of the item.
    */
    "brand"?: string;
    /**
    * Color of the item.
    */
    "color"?: string;
    /**
    * Description of the line item.
    */
    "description"?: string;
    /**
    * ID of the line item.
    */
    "id"?: string;
    /**
    * Link to the picture of the purchased item.
    */
    "imageUrl"?: string;
    /**
    * Item category, used by the payment methods PayPal and Ratepay.
    */
    "itemCategory"?: string;
    /**
    * Manufacturer of the item.
    */
    "manufacturer"?: string;
    /**
    * Marketplace seller id.
    */
    "marketplaceSellerId"?: string;
    /**
    * Link to the purchased item.
    */
    "productUrl"?: string;
    /**
    * Number of items.
    */
    "quantity"?: number;
    /**
    * Email associated with the given product in the basket (usually in electronic gift cards).
    */
    "receiverEmail"?: string;
    /**
    * Shipping company handling the return of the item.
    */
    "returnShippingCompany"?: string;
    /**
    * Tracking number for the return of the item.
    */
    "returnTrackingNumber"?: string;
    /**
    * Tracking URI for the return of the item.
    */
    "returnTrackingUri"?: string;
    /**
    * Shipping company handling the delivery of the item.
    */
    "shippingCompany"?: string;
    /**
    * Shipping method used to deliver the item.
    */
    "shippingMethod"?: string;
    /**
    * Size of the item.
    */
    "size"?: string;
    /**
    * Stock keeping unit.
    */
    "sku"?: string;
    /**
    * Tax amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).
    */
    "taxAmount"?: number;
    /**
    * Tax percentage, represented as a [basis point](https://en.wikipedia.org/wiki/Basis_point) integer. For example:  - **530** for 5.3% (five point three percent)   - **2100** for 21% (twenty-one percent)
    */
    "taxPercentage"?: number;
    /**
    * Tracking number for the delivery of the item.
    */
    "trackingNumber"?: string;
    /**
    * Tracking URI for the delivery of the item.
    */
    "trackingUri"?: string;
    /**
    * Universal Product Code.
    */
    "upc"?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amountExcludingTax",
            "baseName": "amountExcludingTax",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "amountIncludingTax",
            "baseName": "amountIncludingTax",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "brand",
            "baseName": "brand",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemCategory",
            "baseName": "itemCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "marketplaceSellerId",
            "baseName": "marketplaceSellerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "productUrl",
            "baseName": "productUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "receiverEmail",
            "baseName": "receiverEmail",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnShippingCompany",
            "baseName": "returnShippingCompany",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnTrackingNumber",
            "baseName": "returnTrackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnTrackingUri",
            "baseName": "returnTrackingUri",
            "type": "string",
            "format": ""
        },
        {
            "name": "shippingCompany",
            "baseName": "shippingCompany",
            "type": "string",
            "format": ""
        },
        {
            "name": "shippingMethod",
            "baseName": "shippingMethod",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxAmount",
            "baseName": "taxAmount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taxPercentage",
            "baseName": "taxPercentage",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "trackingNumber",
            "baseName": "trackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingUri",
            "baseName": "trackingUri",
            "type": "string",
            "format": ""
        },
        {
            "name": "upc",
            "baseName": "upc",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LineItem.attributeTypeMap;
    }

    public constructor() {
    }
}

