/*
 * The version of the OpenAPI document: v72
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Folio } from "./folio";
import { Room } from "./room";


export class Lodging {
    /**
    * The check-in date. * Min Length: 10 characters * Max Length: 10 characters * Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime): yyyy-MM-dd * **additionalData key:** `lodging.checkInDate`
    */
    "checkInDate"?: string;
    /**
    * The check-out date. * Min Length: 10 characters * Max Length: 10 characters * Format [ISO 8601](https://www.w3.org/TR/NOTE-datetime): yyyy-MM-dd * **additionalData key:** `lodging.checkOutDate`
    */
    "checkOutDate"?: string;
    /**
    * The toll-free phone number for the lodging customer service. * Format: Alphanumeric * For US and CA numbers must be 10 characters in length * Must not start with a space * Must not contain any special characters such as + or - * Must not be all zeros. * **additionalData key:** `lodging.customerServiceTollFreeNumber`
    */
    "customerServicePhoneNumber"?: string;
    /**
    * Indicates that the facility complies with the Hotel and Motel Fire Safety Act of 1990. * **additionalData key:** `lodging.fireSafetyActIndicator`
    */
    "fireSafetyCompliance"?: boolean;
    "folio"?: Folio | null;
    /**
    * Any charges for food and beverages associated with the booking, in [minor units](https://docs.adyen.com/development-resources/currency-codes). * For example, 2000 means USD 20.00. * Encoding: Numeric * Max value: 10000000000 * **additionalData key:** `lodging.foodBeverageCharges`
    */
    "foodBeverageCharges"?: number;
    /**
    * The category of lodging charges for the payment. * **additionalData key:** `lodging.specialProgramCode`
    */
    "lodgingChargeType"?: Lodging.LodgingChargeTypeEnum;
    /**
    * Indicates if the customer didn\'t check in for their booking. * **additionalData key:** `lodging.noShowIndicator`
    */
    "noShow"?: boolean;
    /**
    * The prepaid expenses for the booking, in [minor units](https://docs.adyen.com/development-resources/currency-codes). * For example, 2000 means USD 20.00. * Encoding: Numeric * Max value: 10000000000 * **additionalData key:** `lodging.prepaidExpenses`
    */
    "prepaidExpenses"?: number;
    /**
    * The lodging property location\'s phone number. * Format: Alphanumeric * Min length: 10 characters * For US and CA numbers must be 10 characters in length * Must not start with a space * Must not contain any special characters such as + or - * Must not be all zeros. * **additionalData key:** `lodging.propertyPhoneNumber`
    */
    "propertyPhoneNumber"?: string;
    /**
    * The name of the person renting the room. * Format: ASCII * Must not start with a space or be all spaces. * Must not be all zeros. * **additionalData key:** `lodging.renterName`
    */
    "renterName"?: string;
    /**
    * The list of rooms booked.
    */
    "rooms"?: Array<Room>;
    /**
    * The total room tax amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes). * For example, 2000 means USD 20.00. * Encoding: Numeric * Max value: 10000000000 * **additionalData key:** `lodging.totalRoomTax`
    */
    "totalRoomTax"?: number;
    /**
    * The total tax amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes). * For example, 2000 means USD 20.00. * Encoding: Numeric * Max value: 10000000000 * **additionalData key:** `lodging.totalTax`
    */
    "totalTax"?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checkInDate",
            "baseName": "checkInDate",
            "type": "string",
            "format": "date"
        },
        {
            "name": "checkOutDate",
            "baseName": "checkOutDate",
            "type": "string",
            "format": "date"
        },
        {
            "name": "customerServicePhoneNumber",
            "baseName": "customerServicePhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "fireSafetyCompliance",
            "baseName": "fireSafetyCompliance",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "folio",
            "baseName": "folio",
            "type": "Folio | null",
            "format": ""
        },
        {
            "name": "foodBeverageCharges",
            "baseName": "foodBeverageCharges",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "lodgingChargeType",
            "baseName": "lodgingChargeType",
            "type": "Lodging.LodgingChargeTypeEnum",
            "format": ""
        },
        {
            "name": "noShow",
            "baseName": "noShow",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "prepaidExpenses",
            "baseName": "prepaidExpenses",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "propertyPhoneNumber",
            "baseName": "propertyPhoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "renterName",
            "baseName": "renterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "rooms",
            "baseName": "rooms",
            "type": "Array<Room>",
            "format": ""
        },
        {
            "name": "totalRoomTax",
            "baseName": "totalRoomTax",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalTax",
            "baseName": "totalTax",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return Lodging.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace Lodging {
    export enum LodgingChargeTypeEnum {
        AdvanceDeposit = 'advanceDeposit',
        NoShow = 'noShow',
        Stay = 'stay'
    }
}
