/*
 * The version of the OpenAPI document: v71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { PixRecurring } from "./pixRecurring";


export class PixDetails {
    /**
    * The checkout attempt identifier.
    */
    "checkoutAttemptId"?: string;
    "pixRecurring"?: PixRecurring | null;
    /**
    * This is the `recurringDetailReference` returned in the response when you created the token.
    *
	* @deprecated since Adyen Checkout API v49
	* Use `storedPaymentMethodId` instead.
    */
    "recurringDetailReference"?: string;
    /**
    * Base64-encoded JSON object containing SDK related parameters required by the SDK
    */
    "sdkData"?: string;
    /**
    * This is the `recurringDetailReference` returned in the response when you created the token.
    */
    "storedPaymentMethodId"?: string;
    /**
    * The payment method type.
    */
    "type"?: PixDetails.TypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checkoutAttemptId",
            "baseName": "checkoutAttemptId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pixRecurring",
            "baseName": "pixRecurring",
            "type": "PixRecurring | null",
            "format": ""
        },
        {
            "name": "recurringDetailReference",
            "baseName": "recurringDetailReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "sdkData",
            "baseName": "sdkData",
            "type": "string",
            "format": ""
        },
        {
            "name": "storedPaymentMethodId",
            "baseName": "storedPaymentMethodId",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PixDetails.TypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PixDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace PixDetails {
    export enum TypeEnum {
        Pix = 'pix'
    }
}
