/*
 * The version of the OpenAPI document: v71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class ShopperIdPaymentMethod {
    "type": string;

    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "payTo": "PayToPaymentMethod",
        "upi_collect": "UPIPaymentMethod",
    };

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShopperIdPaymentMethod.attributeTypeMap;
    }

    public constructor() {
        //this.type = "ShopperIdPaymentMethod";
    }
}

