/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { CapabilityProblemEntity } from "./capabilityProblemEntity";
import { VerificationError } from "./verificationError";


export class CapabilityProblem {
    "entity"?: CapabilityProblemEntity | null;
    /**
    * List of verification errors.
    */
    "verificationErrors"?: Array<VerificationError>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entity",
            "baseName": "entity",
            "type": "CapabilityProblemEntity | null",
            "format": ""
        },
        {
            "name": "verificationErrors",
            "baseName": "verificationErrors",
            "type": "Array<VerificationError>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CapabilityProblem.attributeTypeMap;
    }

    public constructor() {
    }
}

