/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class BankAccountIdentification {
    /**
    * The type of account, which depends on the country of the account and the currency of the transfer.
    */
    "type"?: string;

    static readonly discriminator: string | undefined = "type";

    static readonly mapping: {[index: string]: string} | undefined = {
        "auLocal": "AULocalAccountIdentification",
        "brLocal": "BRLocalAccountIdentification",
        "caLocal": "CALocalAccountIdentification",
        "czLocal": "CZLocalAccountIdentification",
        "dkLocal": "DKLocalAccountIdentification",
        "hkLocal": "HKLocalAccountIdentification",
        "huLocal": "HULocalAccountIdentification",
        "iban": "IbanAccountIdentification",
        "noLocal": "NOLocalAccountIdentification",
        "numberAndBic": "NumberAndBicAccountIdentification",
        "nzLocal": "NZLocalAccountIdentification",
        "plLocal": "PLLocalAccountIdentification",
        "seLocal": "SELocalAccountIdentification",
        "sgLocal": "SGLocalAccountIdentification",
        "ukLocal": "UKLocalAccountIdentification",
        "usLocal": "USLocalAccountIdentification",
    };

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BankAccountIdentification.attributeTypeMap;
    }

    public constructor() {
        //this.type = "BankAccountIdentification";
    }
}

