/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Amount } from "./amount";
import { Balance } from "./balance";
import { DisbursementRepayment } from "./disbursementRepayment";
import { Fee } from "./fee";
import { FundsCollection } from "./fundsCollection";


export class Disbursement {
    /**
    * The unique identifier of the account holder that received the disbursement.
    */
    "accountHolderId": string;
    "amount": Amount;
    /**
    * The unique identifier of the balance account that received the disbursement.
    */
    "balanceAccountId": string;
    "balances": Balance;
    "fee": Fee;
    /**
    * Contains information about the accounts that Adyen uses to collect funds related to repayments.
    */
    "fundsCollections"?: Array<FundsCollection>;
    /**
    * The unique identifier of the grant related to the disbursement.
    */
    "grantId": string;
    /**
    * The unique identifier of the disbursement.
    */
    "id": string;
    "repayment": DisbursementRepayment;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountHolderId",
            "baseName": "accountHolderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "Amount",
            "format": ""
        },
        {
            "name": "balanceAccountId",
            "baseName": "balanceAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "balances",
            "baseName": "balances",
            "type": "Balance",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "Fee",
            "format": ""
        },
        {
            "name": "fundsCollections",
            "baseName": "fundsCollections",
            "type": "Array<FundsCollection>",
            "format": ""
        },
        {
            "name": "grantId",
            "baseName": "grantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "repayment",
            "baseName": "repayment",
            "type": "DisbursementRepayment",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Disbursement.attributeTypeMap;
    }

    public constructor() {
    }
}

