/*
 * The version of the OpenAPI document: v30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { DisputeServiceResult } from "./disputeServiceResult";


export class DeleteDefenseDocumentResponse {
    "disputeServiceResult": DisputeServiceResult;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "disputeServiceResult",
            "baseName": "disputeServiceResult",
            "type": "DisputeServiceResult",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeleteDefenseDocumentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

