/*
 * The version of the OpenAPI document: v68
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class ModifyResponse {
    /**
    * This field contains additional data, which may be returned in a particular response.
    */
    "additionalData"?: { [key: string]: string; };
    /**
    * Adyen\'s 16-character string reference associated with the transaction. This value is globally unique; quote it when communicating with us about this response.
    */
    "pspReference": string;
    /**
    * The response: * In case of success, it is either `payout-confirm-received` or `payout-decline-received`. * In case of an error, an informational message is returned.
    */
    "response": string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "pspReference",
            "baseName": "pspReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModifyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

