/**
 * Adyen Payout API
 * A set of API endpoints that allow you to store payout details, confirm, or decline a payout.  For more information, refer to [Online payouts](https://docs.adyen.com/checkout/online-payouts).
 *
 * The version of the OpenAPI document: 51
 * Contact: support@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ShopperInteractionDevice {
    /**
    * Locale on the shopper interaction device.
    */
    'locale'?: string;
    /**
    * Operating system running on the shopper interaction device.
    */
    'os'?: string;
    /**
    * Version of the operating system on the shopper interaction device.
    */
    'osVersion'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "os",
            "baseName": "os",
            "type": "string"
        },
        {
            "name": "osVersion",
            "baseName": "osVersion",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ShopperInteractionDevice.attributeTypeMap;
    }
}

