/*
 * The version of the OpenAPI document: v1
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { AllowedOrigin } from './allowedOrigin';

export class AllowedOriginsResponse {
    /**
    * List of allowed origins.
    */
    'data'?: Array<AllowedOrigin>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<AllowedOrigin>"
        }    ];

    static getAttributeTypeMap() {
        return AllowedOriginsResponse.attributeTypeMap;
    }
}

