/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class GooglePayResponseInfo {
    /**
    * Google Pay [Merchant ID]
    */
    "merchantId"?: string;
    /**
    * Indicates whether the Google Pay Merchant ID is used for several merchant accounts.
    */
    "reuseMerchantId"?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "merchantId",
            "baseName": "merchantId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reuseMerchantId",
            "baseName": "reuseMerchantId",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GooglePayResponseInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

