/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class KioskModeSettings {
    /**
    * List of package names for apps allowed to run in kiosk mode.
    */
    "allowedAppsInKioskMode"?: Array<string>;
    /**
    * The package name of the app to launch on startup. This must be one of the apps included in `allowedAppsInKioskMode`.
    */
    "kioskAppOnStartup"?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowedAppsInKioskMode",
            "baseName": "allowedAppsInKioskMode",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "kioskAppOnStartup",
            "baseName": "kioskAppOnStartup",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KioskModeSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

