/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { InstallAndroidAppDetails } from './installAndroidAppDetails';
import { InstallAndroidCertificateDetails } from './installAndroidCertificateDetails';
import { ReleaseUpdateDetails } from './releaseUpdateDetails';
import { UninstallAndroidAppDetails } from './uninstallAndroidAppDetails';
import { UninstallAndroidCertificateDetails } from './uninstallAndroidCertificateDetails';

/**
* Information about the action to take.
*/
export class ScheduleTerminalActionsRequestActionDetails {
    /**
    * The unique identifier of the app to be uninstalled.
    */
    'appId'?: string;
    /**
    * Type of terminal action: Install an Android app.
    */
    'type'?: ScheduleTerminalActionsRequestActionDetails.TypeEnum = ScheduleTerminalActionsRequestActionDetails.TypeEnum.InstallAndroidApp;
    /**
    * The unique identifier of the certificate to be uninstalled.
    */
    'certificateId'?: string;
    /**
    * Boolean flag that tells if the terminal should update at the first next maintenance call. If false, terminal will update on its configured reboot time.
    */
    'updateAtFirstMaintenanceCall'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appId",
            "baseName": "appId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ScheduleTerminalActionsRequestActionDetails.TypeEnum"
        },
        {
            "name": "certificateId",
            "baseName": "certificateId",
            "type": "string"
        },
        {
            "name": "updateAtFirstMaintenanceCall",
            "baseName": "updateAtFirstMaintenanceCall",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ScheduleTerminalActionsRequestActionDetails.attributeTypeMap;
    }
}

export namespace ScheduleTerminalActionsRequestActionDetails {
    export enum TypeEnum {
        InstallAndroidApp = <any> 'InstallAndroidApp',
        InstallAndroidCertificate = <any> 'InstallAndroidCertificate',
        ReleaseUpdate = <any> 'ReleaseUpdate',
        UninstallAndroidApp = <any> 'UninstallAndroidApp',
        UninstallAndroidCertificate = <any> 'UninstallAndroidCertificate'
    }
}
