/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { TransactionDescriptionResponseInfo } from "./transactionDescriptionResponseInfo";


export class SepaDirectDebitResponseInfo {
    /**
    * Creditor id
    */
    "creditorId"?: string;
    "transactionDescription"?: TransactionDescriptionResponseInfo | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creditorId",
            "baseName": "creditorId",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionDescription",
            "baseName": "transactionDescription",
            "type": "TransactionDescriptionResponseInfo | null",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SepaDirectDebitResponseInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

