/*
 * The version of the OpenAPI document: v1
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class ShopperStatement {
    /**
    * The name you want to be shown on the shopper\'s bank or credit card statement. Maximum length: 22 characters; can\'t be all numbers.
    */
    'doingBusinessAsName'?: string;
    /**
    * The type of shopperstatement you want to use: fixed, append or dynamic
    */
    'type'?: ShopperStatement.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "doingBusinessAsName",
            "baseName": "doingBusinessAsName",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ShopperStatement.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ShopperStatement.attributeTypeMap;
    }
}

export namespace ShopperStatement {
    export enum TypeEnum {
        Append = <any> 'append',
        Dynamic = <any> 'dynamic',
        Fixed = <any> 'fixed'
    }
}
