/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class UninstallAndroidCertificateDetails {
    /**
    * The unique identifier of the certificate to be uninstalled.
    */
    "certificateId"?: string;
    /**
    * Type of terminal action: Uninstall an Android certificate.
    */
    "type"?: UninstallAndroidCertificateDetails.TypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificateId",
            "baseName": "certificateId",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UninstallAndroidCertificateDetails.TypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UninstallAndroidCertificateDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace UninstallAndroidCertificateDetails {
    export enum TypeEnum {
        UninstallAndroidCertificate = 'UninstallAndroidCertificate'
    }
}
