/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class UpdateCompanyApiCredentialRequest {
    /**
    * Indicates if the API credential is enabled.
    */
    'active'?: boolean;
    /**
    * The new list of [allowed origins](https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins) for the API credential.
    */
    'allowedOrigins'?: Array<string>;
    /**
    * List of merchant accounts that the API credential has access to.
    */
    'associatedMerchantAccounts'?: Array<string>;
    /**
    * Description of the API credential.
    */
    'description'?: string;
    /**
    * List of [roles](https://docs.adyen.com/development-resources/api-credentials#roles-1) for the API credential. Only roles assigned to \'ws@Company.<CompanyName>\' can be assigned to other API credentials.
    */
    'roles'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "allowedOrigins",
            "baseName": "allowedOrigins",
            "type": "Array<string>"
        },
        {
            "name": "associatedMerchantAccounts",
            "baseName": "associatedMerchantAccounts",
            "type": "Array<string>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCompanyApiCredentialRequest.attributeTypeMap;
    }
}

