/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import getJsonResponse from "../../helpers/getJsonResponse";
import Service from "../../service";
import Client from "../../client";
import { IRequest } from "../../typings/requestOptions";
import Resource from "../resource";

import { ObjectSerializer } from "../../typings/foreignExchange/objectSerializer";
import { CalculateRateRequest } from "../../typings/foreignExchange/models";
import { CalculateRateResponse } from "../../typings/foreignExchange/models";

/**
 * API handler for RatesApi
 */
export class RatesApi extends Service {

    private readonly API_BASEPATH: string = "https://balanceplatform-api-test.adyen.com/fx/api/v1";
    private baseUrl: string;

    public constructor(client: Client){
        super(client);
        this.baseUrl = this.createBaseUrl(this.API_BASEPATH);
    }

    /**
    * @summary Calculate amount in a different currency
    * @param calculateRateRequest {@link CalculateRateRequest } 
    * @param requestOptions {@link IRequest.Options }
    * @return {@link CalculateRateResponse }
    */
    public async calculate(calculateRateRequest: CalculateRateRequest, requestOptions?: IRequest.Options): Promise<CalculateRateResponse> {
        const endpoint = `${this.baseUrl}/rates/calculate`;
        const resource = new Resource(this, endpoint);
        
        const request: CalculateRateRequest = ObjectSerializer.serialize(calculateRateRequest, "CalculateRateRequest");
        const response = await getJsonResponse<CalculateRateRequest, CalculateRateResponse>(
            resource,
            request,
            { ...requestOptions, method: "POST" }
        );

        return ObjectSerializer.deserialize(response, "CalculateRateResponse");
    }

}
