/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { LoyaltyAccount } from "./loyaltyAccount";
import { POIData } from "./pOIData";
import { PaymentInstrumentData } from "./paymentInstrumentData";
import { Response } from "./response";
import { SaleData } from "./saleData";

/**
* It conveys Information related to the payment and loyalty cards read and processed by the POI System and entered by the Customer. Content of the Card Acquisition Response message.
*/


export class CardAcquisitionResponse {
    "Response": Response;
    "SaleData": SaleData;
    "POIData": POIData;
    /**
    * Type of payment card. Brands available for payment by the card and not chosen by the Customer.
    */
    "PaymentBrand"?: Array<string>;
    "PaymentInstrumentData"?: PaymentInstrumentData | null;
    /**
    * Data related to the loyalty System.
    */
    "LoyaltyAccount"?: Array<LoyaltyAccount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "Response",
            "baseName": "Response",
            "type": "Response",
            "format": ""
        },
        {
            "name": "SaleData",
            "baseName": "SaleData",
            "type": "SaleData",
            "format": ""
        },
        {
            "name": "POIData",
            "baseName": "POIData",
            "type": "POIData",
            "format": ""
        },
        {
            "name": "PaymentBrand",
            "baseName": "PaymentBrand",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "PaymentInstrumentData",
            "baseName": "PaymentInstrumentData",
            "type": "PaymentInstrumentData | null",
            "format": ""
        },
        {
            "name": "LoyaltyAccount",
            "baseName": "LoyaltyAccount",
            "type": "Array<LoyaltyAccount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CardAcquisitionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

