/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { IdentificationSupport } from "./identificationSupport";
import { IdentificationType } from "./identificationType";

/**
* Identification of a Loyalty account. In the Payment Request message, it allows to identify the loyalty account by the Sale Terminal instead of the POI Terminal (e.g. because the account identification is a bar-code read by the Cashier on a scanner device).
*/


export class LoyaltyAccountID {
    "EntryMode": Array<LoyaltyAccountID.EntryModeEnum>;
    "IdentificationType": IdentificationType;
    "IdentificationSupport"?: IdentificationSupport;
    /**
    * Loyalty account identification conforming to the IdentificationType.
    */
    "LoyaltyID": string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "EntryMode",
            "baseName": "EntryMode",
            "type": "LoyaltyAccountID.EntryModeEnum",
            "format": ""
        },
        {
            "name": "IdentificationType",
            "baseName": "IdentificationType",
            "type": "IdentificationType",
            "format": ""
        },
        {
            "name": "IdentificationSupport",
            "baseName": "IdentificationSupport",
            "type": "IdentificationSupport",
            "format": ""
        },
        {
            "name": "LoyaltyID",
            "baseName": "LoyaltyID",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltyAccountID.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace LoyaltyAccountID {
    export enum EntryModeEnum {
        Contactless = 'Contactless',
        File = 'File',
        Icc = 'ICC',
        Keyed = 'Keyed',
        MagStripe = 'MagStripe',
        Manual = 'Manual',
        Mobile = 'Mobile',
        Rfid = 'RFID',
        Scanned = 'Scanned',
        SynchronousIcc = 'SynchronousICC',
        Tapped = 'Tapped'
    }
}
