/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

/**
* Type of PIN Service. Possible values: * **PINEnter** * **PINVerify** * **PINVerifyOnly**
*/

export enum PINRequestType {
    PinEnter = 'PINEnter',
    PinVerify = 'PINVerify',
    PinVerifyOnly = 'PINVerifyOnly'
}
