/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { AdminResponse } from "./adminResponse";
import { BalanceInquiryResponse } from "./balanceInquiryResponse";
import { CardAcquisitionResponse } from "./cardAcquisitionResponse";
import { CardReaderAPDUResponse } from "./cardReaderAPDUResponse";
import { DiagnosisResponse } from "./diagnosisResponse";
import { DisplayResponse } from "./displayResponse";
import { EnableServiceResponse } from "./enableServiceResponse";
import { GetTotalsResponse } from "./getTotalsResponse";
import { InputResponse } from "./inputResponse";
import { LoginResponse } from "./loginResponse";
import { LogoutResponse } from "./logoutResponse";
import { LoyaltyResponse } from "./loyaltyResponse";
import { MessageHeader } from "./messageHeader";
import { PaymentResponse } from "./paymentResponse";
import { PrintResponse } from "./printResponse";
import { ReconciliationResponse } from "./reconciliationResponse";
import { ReversalResponse } from "./reversalResponse";
import { StoredValueResponse } from "./storedValueResponse";
import { TransactionStatusResponse } from "./transactionStatusResponse";

/**
* The SaleToPOIResponse message pair is a container for the response message content. It contains a MessageHeader and a message body.
*/


export class SaleToPOIResponse {
    "MessageHeader": MessageHeader;
    "BalanceInquiryResponse"?: BalanceInquiryResponse | null;
    "CardAcquisitionResponse"?: CardAcquisitionResponse | null;
    "AdminResponse"?: AdminResponse | null;
    "DiagnosisResponse"?: DiagnosisResponse | null;
    "DisplayResponse"?: DisplayResponse | null;
    "EnableServiceResponse"?: EnableServiceResponse | null;
    "GetTotalsResponse"?: GetTotalsResponse | null;
    "InputResponse"?: InputResponse | null;
    "LoginResponse"?: LoginResponse | null;
    "LogoutResponse"?: LogoutResponse | null;
    "LoyaltyResponse"?: LoyaltyResponse | null;
    "PaymentResponse"?: PaymentResponse | null;
    "PrintResponse"?: PrintResponse | null;
    "CardReaderAPDUResponse"?: CardReaderAPDUResponse | null;
    "ReconciliationResponse"?: ReconciliationResponse | null;
    "ReversalResponse"?: ReversalResponse | null;
    "StoredValueResponse"?: StoredValueResponse | null;
    "TransactionStatusResponse"?: TransactionStatusResponse | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "MessageHeader",
            "baseName": "MessageHeader",
            "type": "MessageHeader",
            "format": ""
        },
        {
            "name": "BalanceInquiryResponse",
            "baseName": "BalanceInquiryResponse",
            "type": "BalanceInquiryResponse | null",
            "format": ""
        },
        {
            "name": "CardAcquisitionResponse",
            "baseName": "CardAcquisitionResponse",
            "type": "CardAcquisitionResponse | null",
            "format": ""
        },
        {
            "name": "AdminResponse",
            "baseName": "AdminResponse",
            "type": "AdminResponse | null",
            "format": ""
        },
        {
            "name": "DiagnosisResponse",
            "baseName": "DiagnosisResponse",
            "type": "DiagnosisResponse | null",
            "format": ""
        },
        {
            "name": "DisplayResponse",
            "baseName": "DisplayResponse",
            "type": "DisplayResponse | null",
            "format": ""
        },
        {
            "name": "EnableServiceResponse",
            "baseName": "EnableServiceResponse",
            "type": "EnableServiceResponse | null",
            "format": ""
        },
        {
            "name": "GetTotalsResponse",
            "baseName": "GetTotalsResponse",
            "type": "GetTotalsResponse | null",
            "format": ""
        },
        {
            "name": "InputResponse",
            "baseName": "InputResponse",
            "type": "InputResponse | null",
            "format": ""
        },
        {
            "name": "LoginResponse",
            "baseName": "LoginResponse",
            "type": "LoginResponse | null",
            "format": ""
        },
        {
            "name": "LogoutResponse",
            "baseName": "LogoutResponse",
            "type": "LogoutResponse | null",
            "format": ""
        },
        {
            "name": "LoyaltyResponse",
            "baseName": "LoyaltyResponse",
            "type": "LoyaltyResponse | null",
            "format": ""
        },
        {
            "name": "PaymentResponse",
            "baseName": "PaymentResponse",
            "type": "PaymentResponse | null",
            "format": ""
        },
        {
            "name": "PrintResponse",
            "baseName": "PrintResponse",
            "type": "PrintResponse | null",
            "format": ""
        },
        {
            "name": "CardReaderAPDUResponse",
            "baseName": "CardReaderAPDUResponse",
            "type": "CardReaderAPDUResponse | null",
            "format": ""
        },
        {
            "name": "ReconciliationResponse",
            "baseName": "ReconciliationResponse",
            "type": "ReconciliationResponse | null",
            "format": ""
        },
        {
            "name": "ReversalResponse",
            "baseName": "ReversalResponse",
            "type": "ReversalResponse | null",
            "format": ""
        },
        {
            "name": "StoredValueResponse",
            "baseName": "StoredValueResponse",
            "type": "StoredValueResponse | null",
            "format": ""
        },
        {
            "name": "TransactionStatusResponse",
            "baseName": "TransactionStatusResponse",
            "type": "TransactionStatusResponse | null",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SaleToPOIResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

