/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { IdentificationType } from "./identificationType";
import { StoredValueAccountType } from "./storedValueAccountType";

/**
* Identification of the stored value account or the stored value card and the associated product sold by the Sale System for stored value requests.
*/


export class StoredValueAccountID {
    "StoredValueAccountType": StoredValueAccountType;
    /**
    * Identification of the provider of the stored value account load/reload. When the ProductCode is not sufficient to identify the provider host which delivers the load or reload of the stored value account (for example if it contains the identification of the application.)
    */
    "StoredValueProvider"?: string;
    /**
    * Name of the owner of a stored value account.
    */
    "OwnerName"?: string;
    /**
    * Date after which the card cannot be used. If EMV expiry date is present, it overrides Track2 information. Format is MMYY.
    */
    "ExpiryDate"?: number;
    "EntryMode": Array<StoredValueAccountID.EntryModeEnum>;
    "IdentificationType": IdentificationType;
    /**
    * Stored value account identification. The identification of the stored value account conforming to the IdentificationType.
    */
    "StoredValueID": string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "StoredValueAccountType",
            "baseName": "StoredValueAccountType",
            "type": "StoredValueAccountType",
            "format": ""
        },
        {
            "name": "StoredValueProvider",
            "baseName": "StoredValueProvider",
            "type": "string",
            "format": ""
        },
        {
            "name": "OwnerName",
            "baseName": "OwnerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "ExpiryDate",
            "baseName": "ExpiryDate",
            "type": "number",
            "format": ""
        },
        {
            "name": "EntryMode",
            "baseName": "EntryMode",
            "type": "StoredValueAccountID.EntryModeEnum",
            "format": ""
        },
        {
            "name": "IdentificationType",
            "baseName": "IdentificationType",
            "type": "IdentificationType",
            "format": ""
        },
        {
            "name": "StoredValueID",
            "baseName": "StoredValueID",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StoredValueAccountID.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace StoredValueAccountID {
    export enum EntryModeEnum {
        Contactless = 'Contactless',
        File = 'File',
        Icc = 'ICC',
        Keyed = 'Keyed',
        MagStripe = 'MagStripe',
        Manual = 'Manual',
        Mobile = 'Mobile',
        Rfid = 'RFID',
        Scanned = 'Scanned',
        SynchronousIcc = 'SynchronousICC',
        Tapped = 'Tapped'
    }
}
