/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { CalculateRateRequestItem } from "./calculateRateRequestItem";

/**
* The request to calculate an amount in a different currency.
*/


export class CalculateRateRequest {
    /**
    * An array of objects, where each object defines a currency and value for which you want to perform an exchange calculation.
    */
    "exchangeCalculations": Array<CalculateRateRequestItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "exchangeCalculations",
            "baseName": "exchangeCalculations",
            "type": "Array<CalculateRateRequestItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CalculateRateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

