/*
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Leg } from './leg';

export class Airline {
    /**
    * Details about the flight legs for this ticket.
    */
    'legs'?: Array<Leg>;
    /**
    * The ticket\'s unique identifier
    */
    'ticketNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "legs",
            "baseName": "legs",
            "type": "Array<Leg>"
        },
        {
            "name": "ticketNumber",
            "baseName": "ticketNumber",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Airline.attributeTypeMap;
    }
}

