/*
 * The version of the OpenAPI document: v6
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class KYCCheckSummary {
    /**
    * The code of the check. For possible values, refer to [Verification codes](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-process/verification-codes).
    */
    'kycCheckCode'?: number;
    /**
    * A description of the check.
    */
    'kycCheckDescription'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kycCheckCode",
            "baseName": "kycCheckCode",
            "type": "number"
        },
        {
            "name": "kycCheckDescription",
            "baseName": "kycCheckDescription",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return KYCCheckSummary.attributeTypeMap;
    }
}

