/*
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { KYCCheckStatusData } from './kYCCheckStatusData';

export class KYCLegalArrangementEntityCheckResult {
    /**
    * A list of the checks and their statuses.
    */
    'checks'?: Array<KYCCheckStatusData>;
    /**
    * The unique ID of the legal arrangement to which the entity belongs.
    */
    'legalArrangementCode'?: string;
    /**
    * The unique ID of the legal arrangement entity to which the check applies.
    */
    'legalArrangementEntityCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checks",
            "baseName": "checks",
            "type": "Array<KYCCheckStatusData>"
        },
        {
            "name": "legalArrangementCode",
            "baseName": "legalArrangementCode",
            "type": "string"
        },
        {
            "name": "legalArrangementEntityCode",
            "baseName": "legalArrangementEntityCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return KYCLegalArrangementEntityCheckResult.attributeTypeMap;
    }
}

