/*
 * The version of the OpenAPI document: v6
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { MigratedAccounts } from './migratedAccounts';
import { MigratedStores } from './migratedStores';

export class MigrationData {
    /**
    * The unique identifier of the account holder in the balance platform.
    */
    'accountHolderId'?: string;
    /**
    * The unique identifier of the balance platfrom to which the account holder was migrated.
    */
    'balancePlatform'?: string;
    /**
    * Set to **true** if the account holder has been migrated.
    */
    'migrated'?: boolean;
    /**
    * Contains the mapping of virtual account codes (classic integration) to the balance account codes (balance platform) associated with the migrated account holder.
    */
    'migratedAccounts'?: Array<MigratedAccounts>;
    /**
    * Contains the mapping of business lines and stores associated with the migrated account holder.
    */
    'migratedStores'?: Array<MigratedStores>;
    /**
    * The date when account holder was migrated.
    */
    'migrationDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountHolderId",
            "baseName": "accountHolderId",
            "type": "string"
        },
        {
            "name": "balancePlatform",
            "baseName": "balancePlatform",
            "type": "string"
        },
        {
            "name": "migrated",
            "baseName": "migrated",
            "type": "boolean"
        },
        {
            "name": "migratedAccounts",
            "baseName": "migratedAccounts",
            "type": "Array<MigratedAccounts>"
        },
        {
            "name": "migratedStores",
            "baseName": "migratedStores",
            "type": "Array<MigratedStores>"
        },
        {
            "name": "migrationDate",
            "baseName": "migrationDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return MigrationData.attributeTypeMap;
    }
}

