/*
 * The version of the OpenAPI document: v6
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class PerformVerificationRequest {
    /**
    * The code of the account holder to verify.
    */
    'accountHolderCode': string;
    /**
    * The state required for the account holder. > Permitted values: `Processing`, `Payout`.
    */
    'accountStateType': PerformVerificationRequest.AccountStateTypeEnum;
    /**
    * The tier required for the account holder.
    */
    'tier': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountHolderCode",
            "baseName": "accountHolderCode",
            "type": "string"
        },
        {
            "name": "accountStateType",
            "baseName": "accountStateType",
            "type": "PerformVerificationRequest.AccountStateTypeEnum"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PerformVerificationRequest.attributeTypeMap;
    }
}

export namespace PerformVerificationRequest {
    export enum AccountStateTypeEnum {
        LimitedPayout = 'LimitedPayout',
        LimitedProcessing = 'LimitedProcessing',
        LimitlessPayout = 'LimitlessPayout',
        LimitlessProcessing = 'LimitlessProcessing',
        Payout = 'Payout',
        Processing = 'Processing'
    }
}
