/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { LoyaltyAccountReq } from './loyaltyAccountReq';
import { PaymentAccountReq } from './paymentAccountReq';

/**
* It conveys Information related to the account for which a Balance Inquiry is requested. Content of the Balance Inquiry Request message.
*/
export class BalanceInquiryRequest {
    'PaymentAccountReq'?: PaymentAccountReq;
    'LoyaltyAccountReq'?: LoyaltyAccountReq;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "PaymentAccountReq",
            "baseName": "PaymentAccountReq",
            "type": "PaymentAccountReq"
        },
        {
            "name": "LoyaltyAccountReq",
            "baseName": "LoyaltyAccountReq",
            "type": "LoyaltyAccountReq"
        }    ];

    static getAttributeTypeMap() {
        return BalanceInquiryRequest.attributeTypeMap;
    }
}

