/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { Response } from './response';

/**
* It contains the result of the requested service, APDU response sent by the chip of the card in response to the APDU request. Content of the Card Reader APDU Response message.
*/
export class CardReaderAPDUResponse {
    'Response': Response;
    /**
    * Data field of the APDU command (Lc + Data).
    */
    'APDUData'?: string;
    /**
    * Status of a smartcard response to a command (SW1-SW2).
    */
    'CardStatusWords': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Response",
            "baseName": "Response",
            "type": "Response"
        },
        {
            "name": "APDUData",
            "baseName": "APDUData",
            "type": "string"
        },
        {
            "name": "CardStatusWords",
            "baseName": "CardStatusWords",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CardReaderAPDUResponse.attributeTypeMap;
    }
}

