/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { BarcodeType } from './barcodeType';

export class OutputBarcode {
    'BarcodeType'?: BarcodeType;
    'BarcodeValue': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "BarcodeType",
            "baseName": "BarcodeType",
            "type": "BarcodeType"
        },
        {
            "name": "BarcodeValue",
            "baseName": "BarcodeValue",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OutputBarcode.attributeTypeMap;
    }
}

