/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { TransactionIDType } from './transactionIDType';

/**
* In the Message Response, identification of the POI transaction. Data related to the POI System.
*/
export class POIData {
    'POITransactionID': TransactionIDType;
    /**
    * If Result is Success.
    */
    'POIReconciliationID'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "POITransactionID",
            "baseName": "POITransactionID",
            "type": "TransactionIDType"
        },
        {
            "name": "POIReconciliationID",
            "baseName": "POIReconciliationID",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return POIData.attributeTypeMap;
    }
}

