/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { StoredValueAccountStatus } from './storedValueAccountStatus';
import { StoredValueTransactionType } from './storedValueTransactionType';
import { TransactionIDType } from './transactionIDType';

/**
* For each stored value card loaded or reloaded, in the StoredValue response message. Result of loading/reloading a stored value card..
*/
export class StoredValueResult {
    'StoredValueTransactionType': StoredValueTransactionType;
    /**
    * Copy.
    */
    'ProductCode'?: number;
    /**
    * Copy.
    */
    'EanUpc'?: number;
    /**
    * Total amount of the item line.
    */
    'ItemAmount'?: number;
    /**
    * Copy.
    */
    'Currency'?: string;
    'StoredValueAccountStatus'?: StoredValueAccountStatus;
    'HostTransactionID'?: TransactionIDType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "StoredValueTransactionType",
            "baseName": "StoredValueTransactionType",
            "type": "StoredValueTransactionType"
        },
        {
            "name": "ProductCode",
            "baseName": "ProductCode",
            "type": "number"
        },
        {
            "name": "EanUpc",
            "baseName": "EanUpc",
            "type": "number"
        },
        {
            "name": "ItemAmount",
            "baseName": "ItemAmount",
            "type": "number"
        },
        {
            "name": "Currency",
            "baseName": "Currency",
            "type": "string"
        },
        {
            "name": "StoredValueAccountStatus",
            "baseName": "StoredValueAccountStatus",
            "type": "StoredValueAccountStatus"
        },
        {
            "name": "HostTransactionID",
            "baseName": "HostTransactionID",
            "type": "TransactionIDType"
        }    ];

    static getAttributeTypeMap() {
        return StoredValueResult.attributeTypeMap;
    }
}

