/*
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { StoredValueAccountID } from './storedValueAccountID';

export class StoredValueAccountStatus {
    'StoredValueAccountID': StoredValueAccountID;
    'CurrentBalance'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "StoredValueAccountID",
            "baseName": "StoredValueAccountID",
            "type": "StoredValueAccountID"
        },
        {
            "name": "CurrentBalance",
            "baseName": "CurrentBalance",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return StoredValueAccountStatus.attributeTypeMap;
    }
}

