/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */

import { TopUpWebhookData } from "./topUpWebhookData";


export class TopUpConfigurationEventRequest {
    "data": TopUpWebhookData;
    /**
    * The environment from which the webhook originated.  Possible values: **test**, **live**.
    */
    "environment": string;
    /**
    * When the event was queued.
    */
    "timestamp"?: Date;
    /**
    * Type of webhook.
    */
    "type": TopUpConfigurationEventRequest.TypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "TopUpWebhookData",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TopUpConfigurationEventRequest.TypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TopUpConfigurationEventRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export namespace TopUpConfigurationEventRequest {
    export enum TypeEnum {
        BalancePlatformBalanceAccountRecurringTopUpCreated = 'balancePlatform.balanceAccount.recurringTopUp.created',
        BalancePlatformBalanceAccountRecurringTopUpDeleted = 'balancePlatform.balanceAccount.recurringTopUp.deleted'
    }
}
