/*
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class ValidationFacts {
    /**
    * The reason for the `result` of the validations.  This field is only sent for `validationFacts.type` **walletValidation**, when `validationFacts.result` is **invalid**.
    */
    'reasons'?: Array<string>;
    /**
    * The evaluation result of the validation facts.  Possible values: **valid**, **invalid**, **notValidated**, **notApplicable**.
    */
    'result'?: ValidationFacts.ResultEnum;
    /**
    * The type of the validation fact.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reasons",
            "baseName": "reasons",
            "type": "Array<string>"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "ValidationFacts.ResultEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidationFacts.attributeTypeMap;
    }
}

export namespace ValidationFacts {
    export enum ResultEnum {
        Invalid = 'invalid',
        NotApplicable = 'notApplicable',
        NotValidated = 'notValidated',
        Valid = 'valid'
    }
}
