/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class OnboardingLinkSettings {
    'acceptedCountries'?: Array<string>;
    'allowBankAccountFormatSelection'?: boolean;
    'allowIntraRegionCrossBorderPayout'?: boolean;
    'changeLegalEntityType'?: boolean;
    'editPrefilledCountry'?: boolean;
    'hideOnboardingIntroductionIndividual'?: boolean;
    'hideOnboardingIntroductionOrganization'?: boolean;
    'hideOnboardingIntroductionSoleProprietor'?: boolean;
    'hideOnboardingIntroductionTrust'?: boolean;
    'instantBankVerification'?: boolean;
    'requirePciSignEcomMoto'?: boolean;
    'requirePciSignEcommerce'?: boolean;
    'requirePciSignPos'?: boolean;
    'requirePciSignPosMoto'?: boolean;
    'transferInstrumentLimit'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acceptedCountries",
            "baseName": "acceptedCountries",
            "type": "Array<string>"
        },
        {
            "name": "allowBankAccountFormatSelection",
            "baseName": "allowBankAccountFormatSelection",
            "type": "boolean"
        },
        {
            "name": "allowIntraRegionCrossBorderPayout",
            "baseName": "allowIntraRegionCrossBorderPayout",
            "type": "boolean"
        },
        {
            "name": "changeLegalEntityType",
            "baseName": "changeLegalEntityType",
            "type": "boolean"
        },
        {
            "name": "editPrefilledCountry",
            "baseName": "editPrefilledCountry",
            "type": "boolean"
        },
        {
            "name": "hideOnboardingIntroductionIndividual",
            "baseName": "hideOnboardingIntroductionIndividual",
            "type": "boolean"
        },
        {
            "name": "hideOnboardingIntroductionOrganization",
            "baseName": "hideOnboardingIntroductionOrganization",
            "type": "boolean"
        },
        {
            "name": "hideOnboardingIntroductionSoleProprietor",
            "baseName": "hideOnboardingIntroductionSoleProprietor",
            "type": "boolean"
        },
        {
            "name": "hideOnboardingIntroductionTrust",
            "baseName": "hideOnboardingIntroductionTrust",
            "type": "boolean"
        },
        {
            "name": "instantBankVerification",
            "baseName": "instantBankVerification",
            "type": "boolean"
        },
        {
            "name": "requirePciSignEcomMoto",
            "baseName": "requirePciSignEcomMoto",
            "type": "boolean"
        },
        {
            "name": "requirePciSignEcommerce",
            "baseName": "requirePciSignEcommerce",
            "type": "boolean"
        },
        {
            "name": "requirePciSignPos",
            "baseName": "requirePciSignPos",
            "type": "boolean"
        },
        {
            "name": "requirePciSignPosMoto",
            "baseName": "requirePciSignPosMoto",
            "type": "boolean"
        },
        {
            "name": "transferInstrumentLimit",
            "baseName": "transferInstrumentLimit",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OnboardingLinkSettings.attributeTypeMap;
    }
}

