/*
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit this class manually.
 */


export class PciDocumentInfo {
    /**
    * The date the questionnaire was created, in ISO 8601 extended format. For example, 2022-12-18T10:15:30+01:00
    */
    'createdAt'?: Date;
    /**
    * The unique identifier of the signed questionnaire.
    */
    'id'?: string;
    /**
    * The expiration date of the questionnaire, in ISO 8601 extended format. For example, 2022-12-18T10:15:30+01:00
    */
    'validUntil'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "validUntil",
            "baseName": "validUntil",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return PciDocumentInfo.attributeTypeMap;
    }
}

