/*
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 * Adyen NodeJS API Library
 * Copyright (c) 2020 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 */

/**
 * Terminal API
 * Definition of Terminal API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export enum ErrorConditionType {
    Aborted = "Aborted" as any,
    Busy = "Busy" as any,
    Cancel = "Cancel" as any,
    DeviceOut = "DeviceOut" as any,
    InProgress = "InProgress" as any,
    InsertedCard = "InsertedCard" as any,
    InvalidCard = "InvalidCard" as any,
    LoggedOut = "LoggedOut" as any,
    MessageFormat = "MessageFormat" as any,
    NotAllowed = "NotAllowed" as any,
    NotFound = "NotFound" as any,
    PaymentRestriction = "PaymentRestriction" as any,
    Refusal = "Refusal" as any,
    UnavailableDevice = "UnavailableDevice" as any,
    UnavailableService = "UnavailableService" as any,
    UnreachableHost = "UnreachableHost" as any,
    WrongPIN = "WrongPIN" as any
}
