/**
 * Terminal API
 * Definition of Terminal API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SoundActionType } from './soundActionType';
import { SoundContent } from './soundContent';

export class SoundRequest {
    'ResponseMode'?: SoundRequest.ResponseModeEnum;
    'SoundAction': SoundActionType;
    'SoundContent': SoundContent;
    'SoundVolume'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ResponseMode",
            "baseName": "ResponseMode",
            "type": "SoundRequest.ResponseModeEnum"
        },
        {
            "name": "SoundAction",
            "baseName": "SoundAction",
            "type": "SoundActionType"
        },
        {
            "name": "SoundContent",
            "baseName": "SoundContent",
            "type": "SoundContent"
        },
        {
            "name": "SoundVolume",
            "baseName": "SoundVolume",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SoundRequest.attributeTypeMap;
    }
}

export namespace SoundRequest {
    export enum ResponseModeEnum {
        Immediate = <any> 'Immediate',
        NotRequired = <any> 'NotRequired',
        PrintEnd = <any> 'PrintEnd',
        SoundEnd = <any> 'SoundEnd'
    }
}
