/*
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 * Adyen NodeJS API Library
 * Copyright (c) 2020 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 */

/**
 * Terminal API
 * Definition of Terminal API Schema
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OriginalPOITransaction } from './originalPOITransaction';
import { StoredValueAccountId } from './storedValueAccountId';
import { StoredValueTransactionType } from './storedValueTransactionType';

export class StoredValueData {
    'currency': string;
    'eanUpc'?: string;
    'itemAmount': number;
    'originalPOITransaction'?: OriginalPOITransaction;
    'productCode'?: string;
    'storedValueAccountID'?: StoredValueAccountId;
    'storedValueProvider'?: string;
    'storedValueTransactionType': StoredValueTransactionType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "Currency",
            "type": "string"
        },
        {
            "name": "eanUpc",
            "baseName": "EanUpc",
            "type": "string"
        },
        {
            "name": "itemAmount",
            "baseName": "ItemAmount",
            "type": "number"
        },
        {
            "name": "originalPOITransaction",
            "baseName": "OriginalPOITransaction",
            "type": "OriginalPOITransaction"
        },
        {
            "name": "productCode",
            "baseName": "ProductCode",
            "type": "string"
        },
        {
            "name": "storedValueAccountID",
            "baseName": "StoredValueAccountID",
            "type": "StoredValueAccountId"
        },
        {
            "name": "storedValueProvider",
            "baseName": "StoredValueProvider",
            "type": "string"
        },
        {
            "name": "storedValueTransactionType",
            "baseName": "StoredValueTransactionType",
            "type": "StoredValueTransactionType"
        }    ];

    static getAttributeTypeMap() {
        return StoredValueData.attributeTypeMap;
    }
}

