name: Github Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gh_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Grab version
        uses: actions/github-script@v6
        id: release
        with:
          script: |
            const release = require('./.github/scripts/release.js')
            core.setOutput('version', release.packageVersion())
      - name: Create new release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v${{steps.release.outputs.version}} \
            --title 'Adyen Node API Library v${{steps.release.outputs.version}}' \
            --generate-notes --target main
      - name: Update develop branch
        run: |
          git checkout develop
          git merge main
          git push origin develop
