on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  gh_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
      - name: Grab current version
        id: current-version
        run: make version
      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
          CURRENT_VERSION: ${{steps.current-version.outputs.currentVersion}}
        run: |
          prerelease=$(node -pe "process.env.CURRENT_VERSION.includes('-') ? '--prerelease' : ''")
          gh release create "v${CURRENT_VERSION}" \
            --title "Adyen ${{ inputs.project-name }} API Library v${CURRENT_VERSION}" \
            --generate-notes $prerelease --target main
      - name: Update develop branch
        run: |
          git checkout develop
          git rebase origin/main
          git push origin develop
