name: Node.js Models

on: [ workflow_dispatch, pull_request ]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Models
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate models
        run: make models
      - name: Propose changes
        run: ./pr.sh 