name: Node.js Models

on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Models
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Typescript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript
          openapi-url: https://raw.githubusercontent.com/Adyen/adyen-openapi/main/yaml/CheckoutService-v69.yaml
          template-dir: templates/typescript
      - name: Publish updates
        run: |
          ls -lahR typescript
